
SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [PRODUTOS] WHERE [CODIGO] = '1000889'

UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 7
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CODIGO], A.[PRECO LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CODIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CODIGO] = '1000889'

UPDATE A SET A.[PRECO LISTA] = B.[PREÇO DE LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CODIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CODIGO] = '1000889'

-- Podemos observar que os vendedores possuem bairros associados a eles. 
-- Vamos aumentar em 30% o volume de compra dos clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios.
-- Dica: vamos usar um UPDATE com FROM, usando o seguinte INNER JOIN:

SELECT * FROM [CLIENTES]
SELECT * FROM [VENDEDORES]

SELECT A.CPF FROM [dbo].[CLIENTES] A
INNER JOIN [dbo].[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO]

UPDATE A SET A.[VOLUME DE COMPRA] = 
    A.[VOLUME DE COMPRA] * 1.30
FROM [dbo].[CLIENTES] A 
INNER JOIN [dbo].[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO]