

CREATE TABLE TAB_IDENTITY 
( ID INT IDENTITY (1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL)

commit

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE X')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Y')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Z')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE W')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A')

SELECT * FROM TAB_IDENTITY

DELETE FROM TAB_IDENTITY WHERE ID = 1

DROP TABLE TAB_IDENTITY

CREATE TABLE TAB_IDENTITY 
( ID INT IDENTITY (100,5) NOT NULL,
DESCRITOR VARCHAR(20) NULL)

SELECT * FROM TAB_IDENTITY


-- Temos um campo de auto-incremento, que irá crescer de 55 em 55 de um registro para o próximo, a partir do valor 1432. Como devemos declará-lo na criação da tabela?

-- CREATE TABLE TAB_IDENTITY 
-- ( ID INT IDENTITY (1432,55) NOT NULL,
-- DESCRITOR VARCHAR(20) NULL)

