
CREATE TABLE ##TABELA02 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL)

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('1', 'JOÃO')

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('2', 'PEDRO')

SELECT * FROM ##TABELA02
commit
SELECT * FROM #TABELA_NUMEROS2