
SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]

SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'

INSERT INTO [PRODUTOS] ([CODIGO], [DESCRITOR], [SABOR], [TAMANHO], [EMBALAGEM], [PRECO LISTA])
SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'


INSERT INTO CLIENTES ([CPF],[NOME],[ENDEREÇO],[BAIRRO],
    [CIDADE],[ESTADO],[CEP],[DATA NASCIMENTO],[IDADE],
    [SEXO],[LIMITE DE CRÉDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA])
SELECT [CPF],[NOME],[ENDERECO 1] AS ENDEREÇO,[BAIRRO],[CIDADE],[ESTADO],
    [CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],
    [VOLUME DE COMPRA],[PRIMEIRA COMPRA]
FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES] 
    WHERE [CPF] NOT IN ('1471156710','19290992743','2600586709')


SELECT *
FROM CLIENTES